### ISSUE TITLE
About the cost

### ISSUE THREAD

**Issue by ShaoqLin** [fan19-hub/nlp-project#1]
Hello,
LEMMA is an outstanding project, and your contributions are truly impressive. I am currently conducting research on LVLM work and would like to inquire about the costs associated with running experiments on Twitter and Fakereddit. Specifically, I am interested in the expenses related to purchasing OpenAI's API for these experiments. Could you provide some insights on this?
Thank you!

**Comment by fan19-hub** [comment]
Hi Shaoq,
We appreciate your interest in our work! The cost for running the entire twitter dataset is about 57 US dollars under LEMMA framework. The cost of fakeddit is pretty much the same. Note that multiple (2 or 6) api requests are sent when processing one sample. You can check the prompts folder to see how long they are. The base model is either gpt-4-turbo or gpt-4v. Feel free to ask if you get further questions.

**Comment by ShaoqLin** [comment]
> Hi Shaoq, We appreciate your interest in our work! The cost for running the entire twitter dataset is about 57 US dollars under LEMMA framework. The cost of fakeddit is pretty much the same. Note that multiple (2 or 6) api requests are sent when processing one sample. You can check the prompts folder to see how long they are. The base model is either gpt-4-turbo or gpt-4. Feel free to ask if you get further questions.

Thanks for your timely reply, that's really helpful:)
